In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("data/at_urg_respiratorio_semanal.parquet")

In [3]:
df.shape

(3640132, 25)

In [4]:
df.columns.tolist()

['EstablecimientoCodigo',
 'EstablecimientoGlosa',
 'RegionCodigo',
 'RegionGlosa',
 'ComunaCodigo',
 'ComunaGlosa',
 'ServicioSaludCodigo',
 'ServicioSaludGlosa',
 'TipoEstablecimiento',
 'DependenciaAdministrativa',
 'NivelAtencion',
 'TipoUrgencia',
 'Latitud',
 'Longitud',
 'NivelComplejidad',
 'Anio',
 'SemanaEstadistica',
 'OrdenCausa',
 'Causa',
 'NumTotal',
 'NumMenor1Anio',
 'Num1a4Anios',
 'Num5a14Anios',
 'Num15a64Anios',
 'Num65oMas']

In [5]:
df.head()

,EstablecimientoCodigo,EstablecimientoGlosa,RegionCodigo,RegionGlosa,ComunaCodigo,ComunaGlosa,ServicioSaludCodigo,ServicioSaludGlosa,TipoEstablecimiento,DependenciaAdministrativa,...,Anio,SemanaEstadistica,OrdenCausa,Causa,NumTotal,NumMenor1Anio,Num1a4Anios,Num5a14Anios,Num15a64Anios,Num65oMas
0,110860,SAR Renca,13,Región Metropolitana de Santiago,13128,Renca,10,Servicio de Salud Metropolitano Occidente,Servicio de Atención Primaria de Urgencia de A...,Municipal,...,2014,37,9,Otra causa respiratoria no contenidas en las c...,78,4,2,12,58,2
1,200143,SAPU Aguilucho,13,Región Metropolitana de Santiago,13123,Providencia,12,Servicio de Salud Metropolitano Oriente,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2023,49,7,Bronquitis/bronquiolitis aguda (J20-J21),14,0,3,2,7,2
2,200094,SAPU Marco Antonio Carvajal Moreno,15,Región De Arica Parinacota,15101,Arica,1,Servicio de Salud Arica y Parinacota,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2023,25,8,Crisis obstructiva bronquial (J40-J46),3,0,0,0,3,0
3,117107,Hospital Comunitario de Salud Familiar de El C...,16,Región De Ñuble,16104,El Carmen,17,Servicio de Salud Ñuble,Hospital,Servicio de Salud,...,2024,17,5,Influenza (J09-J11),4,0,0,0,4,0
4,121806,SAPU Santa Rosa,9,Región De La Araucanía,9101,Temuco,21,Servicio de Salud Araucanía Sur,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2014,11,5,Influenza (J09-J11),0,0,0,0,0,0

In [6]:
df.dtypes

EstablecimientoCodigo        object
EstablecimientoGlosa         object
RegionCodigo                 object
RegionGlosa                  object
ComunaCodigo                 object
ComunaGlosa                  object
ServicioSaludCodigo          object
ServicioSaludGlosa           object
TipoEstablecimiento          object
DependenciaAdministrativa    object
NivelAtencion                object
TipoUrgencia                 object
Latitud                      object
Longitud                     object
NivelComplejidad             object
Anio                          int32
SemanaEstadistica             int32
OrdenCausa                    int32
Causa                        object
NumTotal                      int32
NumMenor1Anio                 int32
Num1a4Anios                   int32
Num5a14Anios                  int32
Num15a64Anios                 int32
Num65oMas                     int32
dtype: object

In [7]:
df['RegionCodigo'].unique()

array(['13', '15', '16', '9', '5', '8', '3', '7', '10', '2', '4', '6',
       '11', None, '1', '14', '12'], dtype=object)

In [8]:
len(df['SemanaEstadistica'].unique())

53

In [9]:
df[df['RegionCodigo'] == '13']

,EstablecimientoCodigo,EstablecimientoGlosa,RegionCodigo,RegionGlosa,ComunaCodigo,ComunaGlosa,ServicioSaludCodigo,ServicioSaludGlosa,TipoEstablecimiento,DependenciaAdministrativa,...,Anio,SemanaEstadistica,OrdenCausa,Causa,NumTotal,NumMenor1Anio,Num1a4Anios,Num5a14Anios,Num15a64Anios,Num65oMas
0,110860,SAR Renca,13,Región Metropolitana de Santiago,13128,Renca,10,Servicio de Salud Metropolitano Occidente,Servicio de Atención Primaria de Urgencia de A...,Municipal,...,2014,37,9,Otra causa respiratoria no contenidas en las c...,78,4,2,12,58,2
1,200143,SAPU Aguilucho,13,Región Metropolitana de Santiago,13123,Providencia,12,Servicio de Salud Metropolitano Oriente,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2023,49,7,Bronquitis/bronquiolitis aguda (J20-J21),14,0,3,2,7,2
5,113808,SAPU Clara Estrella,13,Región Metropolitana de Santiago,13116,Lo Espejo,13,Servicio de Salud Metropolitano Sur,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2015,29,8,Crisis obstructiva bronquial (J40-J46),0,0,0,0,0,0
23,112813,SAPU Santa Julia,13,Región Metropolitana de Santiago,13118,Macul,12,Servicio de Salud Metropolitano Oriente,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2017,48,4,IRA Alta (J00-J06),49,5,7,14,18,5
24,109813,SAPU Nº 2 Irene Frei de Cid,13,Región Metropolitana de Santiago,13125,Quilicura,9,Servicio de Salud Metropolitano Norte,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2018,23,7,Bronquitis/bronquiolitis aguda (J20-J21),40,5,18,3,14,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3640108,114825,SAPU Granja Sur,13,Región Metropolitana de Santiago,13111,La Granja,14,Servicio de Salud Metropolitano Sur Oriente,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2014,10,33,- Causas sistema respiratorio (J00-J98),0,0,0,0,0,0
3640113,113830,SAPU Raúl Brañes F.,13,Región Metropolitana de Santiago,13401,San Bernardo,13,Servicio de Salud Metropolitano Sur,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2014,26,6,Neumonía (J12-J18),4,0,1,1,1,1
3640115,111806,SAPU San José de Chuchunco,13,Región Metropolitana de Santiago,13106,Estación Central,11,Servicio de Salud Metropolitano Central,Servicio de Atención Primaria de Urgencia (SAPU),Servicio de Salud,...,2019,1,9,Otra causa respiratoria no contenidas en las c...,20,1,0,0,8,11
3640120,200011,SAR Enrique Molina,13,Región Metropolitana de Santiago,13129,San Joaquín,13,Servicio de Salud Metropolitano Sur,Servicio de Atención Primaria de Urgencia de A...,Municipal,...,2025,37,9,Otra causa respiratoria no contenidas en las c...,8,0,1,2,4,1
3640127,112806,SAPU Aníbal Ariztía,13,Región Metropolitana de Santiago,13114,Las Condes,12,Servicio de Salud Metropolitano Oriente,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2019,42,9,Otra causa respiratoria no contenidas en las c...,8,0,0,0,4,4

In [10]:
print("\nRANGO DE AÑOS")
print(df["Anio"].min(), df["Anio"].max())

print("\nAÑOS DISPONIBLES")
print(sorted(df["Anio"].unique()))

print("\nSEMANAS")
print(df["SemanaEstadistica"].min(), df["SemanaEstadistica"].max())

print("\nCAUSAS")
print(df["Causa"].value_counts())

print("\nREGIONES")
print(df["RegionGlosa"].value_counts())

print("\nTIPOS DE URGENCIA")
print(df["TipoUrgencia"].value_counts())

print("\nVALORES NULOS")
print(df.isnull().sum())

RANGO DE AÑOS
2014 2026

AÑOS DISPONIBLES
[np.int32(2014), np.int32(2015), np.int32(2016), np.int32(2017), np.int32(2018), np.int32(2019), np.int32(2020), np.int32(2021), np.int32(2022), np.int32(2023), np.int32(2024), np.int32(2025), np.int32(2026)]

SEMANAS
1 53

CAUSAS
Causa
Otra causa respiratoria no contenidas en las categorías anteriores (J22; J30-J39, J47, J60-J98)    350099
Bronquitis/bronquiolitis aguda (J20-J21)                                                           350099
Crisis obstructiva bronquial (J40-J46)                                                             350099
Influenza (J09-J11)                                                                                350099
- Causas sistema respiratorio (J00-J98)                                                            350099
TOTAL CAUSA SISTEMA  RESPIRATORIO (J00-J98)                                                        350099
Neumonía (J12-J18)                                                                                 350099
IRA Alta (J00-J06)                                                                                 350099
TOTAL ATENCIONES POR COVID-19, Virus Identificado U07.1                                            210336
TOTAL ATENCIONES POR COVID-19  Virus no Identificado U07.2                                         210331
- Por covid-19, virus identificado U07.1                                                           210331
- Por covid-19, virus no identificado U07.2                                                        208342
Name: count, dtype: int64

REGIONES
RegionGlosa
Región Metropolitana de Santiago                       947852
Región Del Bíobío                                      399275
Región De Valparaíso                                   321731
Región Del Maule                                       313314
Región Del Libertador Gral. B. O'Higgins               272359
Región De Los Lagos                                    263211
Región De La Araucanía                                 208336
Región De Coquimbo                                     188768
Región De Ñuble                                        132288
Región De Los Ríos                                     129124
Región De Antofagasta                                  119551
Región De Atacama                                       95722
Región De Tarapacá                                      85383
Región De Magallanes y de la Antártica Chilena          49980
Región De Aysén del General Carlos Ibañez del Campo     36940
Región De los Ríos                                      23724
Región De Arica Parinacota                              23612
Name: count, dtype: int64

TIPOS DE URGENCIA
TipoUrgencia
Urgencia Ambulatoria (SAPU)    1384318
Urgencia Hospitalaria (UEH)    1139042
Urgencia Ambulatoria (SUR)      558702
Urgencia ambulatoria (SAR)      466778
Urgencia Ambulatoria (SAR)       39335
Urgencia ambulatoria             11064
Urgencia Especializada            8043
No Aplica                         2532
Pendiente                         1356
Name: count, dtype: int64

VALORES NULOS
EstablecimientoCodigo        28962
EstablecimientoGlosa         28962
RegionCodigo                 28962
RegionGlosa                  28962
ComunaCodigo                 28962
ComunaGlosa                  28962
ServicioSaludCodigo          28962
ServicioSaludGlosa           28962
TipoEstablecimiento          28962
DependenciaAdministrativa    28962
NivelAtencion                28962
TipoUrgencia                 28962
Latitud                      28962
Longitud                     28962
NivelComplejidad             28962
Anio                             0
SemanaEstadistica                0
OrdenCausa                       0
Causa                            0
NumTotal                         0
NumMenor1Anio                    0
Num1a4Anios                      0
Num5a14Anios                     0
Num15a64Anios                    0
Num65oMas                        0
dtype: int64

In [11]:
print("\nEJEMPLO DE REGISTROS")
display(
    df[
        [
            "Anio",
            "SemanaEstadistica",
            "RegionGlosa",
            "EstablecimientoGlosa",
            "OrdenCausa",
            "Causa",
            "NumTotal"
        ]
    ].head(20)
)

EJEMPLO DE REGISTROS

,Anio,SemanaEstadistica,RegionGlosa,EstablecimientoGlosa,OrdenCausa,Causa,NumTotal
0,2014,37,Región Metropolitana de Santiago,SAR Renca,9,Otra causa respiratoria no contenidas en las c...,78
1,2023,49,Región Metropolitana de Santiago,SAPU Aguilucho,7,Bronquitis/bronquiolitis aguda (J20-J21),14
2,2023,25,Región De Arica Parinacota,SAPU Marco Antonio Carvajal Moreno,8,Crisis obstructiva bronquial (J40-J46),3
3,2024,17,Región De Ñuble,Hospital Comunitario de Salud Familiar de El C...,5,Influenza (J09-J11),4
4,2014,11,Región De La Araucanía,SAPU Santa Rosa,5,Influenza (J09-J11),0
5,2015,29,Región Metropolitana de Santiago,SAPU Clara Estrella,8,Crisis obstructiva bronquial (J40-J46),0
6,2019,3,Región De Valparaíso,SAPU Reñaca Alto,33,- Causas sistema respiratorio (J00-J98),0
7,2017,16,Región Del Bíobío,Hospital San Vicente de Arauco,3,TOTAL CAUSA SISTEMA RESPIRATORIO (J00-J98),134
8,2025,47,Región De Atacama,Hospital Dr. Jerónimo Méndez Arancibia (Chañaral),11,"TOTAL ATENCIONES POR COVID-19, Virus Identific...",0
9,2023,41,Región Del Maule,SAPU Carlos Trupp,6,Neumonía (J12-J18),2
10,2026,22,Región De Los Lagos,SAPU Rahue Alto,9,Otra causa respiratoria no contenidas en las c...,4
11,2021,17,Región Del Maule,SUR La Huerta de Hualañé,33,- Causas sistema respiratorio (J00-J98),0
12,2026,23,Región Del Maule,SUR Río Claro,33,- Causas sistema respiratorio (J00-J98),0
13,2022,47,Región Del Bíobío,SAR Hualpencillo,33,- Causas sistema respiratorio (J00-J98),0
14,2020,38,Región Del Bíobío,SUR Isabel Jiménez,8,Crisis obstructiva bronquial (J40-J46),1
15,2024,21,Región De Los Lagos,SAPU Los Muermos,5,Influenza (J09-J11),2
16,2016,19,Región Del Bíobío,SAPU Talcahuano Sur,33,- Causas sistema respiratorio (J00-J98),0
17,2017,37,Región De Antofagasta,Hospital Dr. Leonardo Guzmán (Antofagasta),6,Neumonía (J12-J18),5
18,2022,13,Región De Valparaíso,Hospital Claudio Vicuña ( San Antonio),8,Crisis obstructiva bronquial (J40-J46),9
19,2015,27,Región De Coquimbo,SAPU Canela,7,Bronquitis/bronquiolitis aguda (J20-J21),12

In [12]:
print("\nORDEN CAUSA")
print(
    df[["OrdenCausa", "Causa"]]
    .drop_duplicates()
    .sort_values("OrdenCausa")
    .to_string(index=False)
)

ORDEN CAUSA
 OrdenCausa                                                                                           Causa
          3                                                     TOTAL CAUSA SISTEMA  RESPIRATORIO (J00-J98)
          4                                                                              IRA Alta (J00-J06)
          5                                                                             Influenza (J09-J11)
          6                                                                              Neumonía (J12-J18)
          7                                                        Bronquitis/bronquiolitis aguda (J20-J21)
          8                                                          Crisis obstructiva bronquial (J40-J46)
          9 Otra causa respiratoria no contenidas en las categorías anteriores (J22; J30-J39, J47, J60-J98)
         10                                      TOTAL ATENCIONES POR COVID-19  Virus no Identificado U07.2
         11                                         TOTAL ATENCIONES POR COVID-19, Virus Identificado U07.1
         33                                                         - Causas sistema respiratorio (J00-J98)
         34                                                     - Por covid-19, virus no identificado U07.2
         35                                                        - Por covid-19, virus identificado U07.1

In [13]:
causa_total = df[
    df["Causa"].str.contains(
        "TOTAL CAUSA SISTEMA",
        case=False,
        na=False
    )
]

print(causa_total.shape)

print(
    causa_total[
        [
            "Anio",
            "SemanaEstadistica",
            "RegionGlosa",
            "EstablecimientoGlosa",
            "NumTotal"
        ]
    ].head(20).to_string(index=False)
)

(350099, 25)
 Anio  SemanaEstadistica                      RegionGlosa                EstablecimientoGlosa  NumTotal
 2017                 16                Región Del Bíobío      Hospital San Vicente de Arauco       134
 2020                 16             Región De Valparaíso         SAR Nestor Fernández Thomas        21
 2021                 48                Región Del Bíobío     Hospital San Agustín de Florida        48
 2021                 16 Región Metropolitana de Santiago                          SAPU Garín         8
 2021                 34 Región Metropolitana de Santiago                      SAPU Lo Franco        28
 2015                 25                 Región Del Maule                SAR Luis Tobar Rojas       347
 2025                  2                             None                                None        51
 2023                 32            Región De Antofagasta                      SAPU Corvallis       164
 2024                 14                             None                                None        80
 2022                 39             Región De Valparaíso                    SUR LAS VENTANAS       134
 2024                 24               Región De Coquimbo                       SAPU El Sauce       184
 2024                 16 Región Metropolitana de Santiago                  SAPU Juan Pablo II       249
 2016                 27                Región Del Bíobío            SAPU Juan Soto Fernández       217
 2014                 13               Región De Los Ríos                   Hospital de Lanco       105
 2026                 27 Región Metropolitana de Santiago                      SAPU Aguilucho       148
 2019                  4 Región Metropolitana de Santiago                    SAPU María Pinto        57
 2018                 41               Región De Los Ríos               Hospital de Los Lagos        91
 2016                 28                 Región Del Maule                 Hospital de Curepto        15
 2022                 26           Región De La Araucanía Hospital San Francisco de Pucón (D)       177
 2018                 49            Región De Antofagasta                 SAPU Antonio Rendic       119

In [14]:
df[df["OrdenCausa"] == 3]

,EstablecimientoCodigo,EstablecimientoGlosa,RegionCodigo,RegionGlosa,ComunaCodigo,ComunaGlosa,ServicioSaludCodigo,ServicioSaludGlosa,TipoEstablecimiento,DependenciaAdministrativa,...,Anio,SemanaEstadistica,OrdenCausa,Causa,NumTotal,NumMenor1Anio,Num1a4Anios,Num5a14Anios,Num15a64Anios,Num65oMas
7,128113,Hospital San Vicente de Arauco,8,Región Del Bíobío,8202,Arauco,28,Servicio de Salud Arauco,Hospital,Servicio de Salud,...,2017,16,3,TOTAL CAUSA SISTEMA RESPIRATORIO (J00-J98),134,6,27,19,67,15
21,106829,SAR Nestor Fernández Thomas,5,Región De Valparaíso,5601,San Antonio,6,Servicio de Salud Valparaíso San Antonio,Servicio de Atención Primaria de Urgencia de A...,Municipal,...,2020,16,3,TOTAL CAUSA SISTEMA RESPIRATORIO (J00-J98),21,0,0,2,15,4
26,118108,Hospital San Agustín de Florida,8,Región Del Bíobío,8104,Florida,18,Servicio de Salud Concepción,Hospital,Servicio de Salud,...,2021,48,3,TOTAL CAUSA SISTEMA RESPIRATORIO (J00-J98),48,1,7,14,18,8
30,200126,SAPU Garín,13,Región Metropolitana de Santiago,13126,Quinta Normal,10,Servicio de Salud Metropolitano Occidente,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2021,16,3,TOTAL CAUSA SISTEMA RESPIRATORIO (J00-J98),8,1,0,0,4,3
45,200128,SAPU Lo Franco,13,Región Metropolitana de Santiago,13126,Quinta Normal,10,Servicio de Salud Metropolitano Occidente,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2021,34,3,TOTAL CAUSA SISTEMA RESPIRATORIO (J00-J98),28,2,8,4,9,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3640071,114802,SAPU Los Castaños,13,Región Metropolitana de Santiago,13110,La Florida,14,Servicio de Salud Metropolitano Sur Oriente,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2014,7,3,TOTAL CAUSA SISTEMA RESPIRATORIO (J00-J98),104,9,16,15,57,7
3640079,113806,SAPU La Feria,13,Región Metropolitana de Santiago,13121,Pedro Aguirre Cerda,13,Servicio de Salud Metropolitano Sur,Servicio de Atención Primaria de Urgencia (SAPU),Municipal,...,2015,34,3,TOTAL CAUSA SISTEMA RESPIRATORIO (J00-J98),413,16,69,92,210,26
3640092,200773,SUR Pelarco,7,Región Del Maule,7106,Pelarco,16,Servicio de Salud Del Maule,Servicio de Urgencia Rural (SUR),Municipal,...,2023,48,3,TOTAL CAUSA SISTEMA RESPIRATORIO (J00-J98),77,6,9,13,39,10
3640101,201043,SUR La Huerta de Hualañé,7,Región Del Maule,7302,Hualañé,16,Servicio de Salud Del Maule,Servicio de Urgencia Rural (SUR),Servicio de Salud,...,2023,39,3,TOTAL CAUSA SISTEMA RESPIRATORIO (J00-J98),26,0,2,5,12,7
3640119,116100,Hospital San Juan de Dios (Curicó),7,Región Del Maule,7301,Curicó,16,Servicio de Salud Del Maule,Hospital,Servicio de Salud,...,2025,26,3,TOTAL CAUSA SISTEMA RESPIRATORIO (J00-J98),188,23,52,37,45,31

In [ ]:
df_total = df[df["OrdenCausa"] == 3].copy()

df_total = df_total.dropna(subset=["RegionGlosa"])

df_semanal = (
    df_total
    .groupby(
        ["Anio", "SemanaEstadistica", "RegionGlosa"],
        as_index=False
    )["NumTotal"]
    .sum()
)

print(df_semanal.shape)
print(df_semanal.head(20))

(10975, 4)
    Anio  SemanaEstadistica  \
0   2014                  1
1   2014                  1
2   2014                  1
3   2014                  1
4   2014                  1
5   2014                  1
6   2014                  1
7   2014                  1
8   2014                  1
9   2014                  1
10  2014                  1
11  2014                  1
12  2014                  1
13  2014                  1
14  2014                  1
15  2014                  1
16  2014                  2
17  2014                  2
18  2014                  2
19  2014                  2

                                          RegionGlosa  NumTotal
0                               Región De Antofagasta       808
1                          Región De Arica Parinacota       225
2                                   Región De Atacama       447
3   Región De Aysén del General Carlos Ibañez del ...       270
4                                  Región De Coquimbo      1188
5                              Región De La Araucanía      1427
6                                 Región De Los Lagos      2321
7                                  Región De Los Ríos      1386
8      Región De Magallanes y de la Antártica Chilena       347
9                                  Región De Tarapacá       595
10                               Región De Valparaíso      2696
11                                    Región De Ñuble      1113
12                                  Región Del Bíobío      4974
13           Región Del Libertador Gral. B. O'Higgins      1827
14                                   Región Del Maule      2878
15                   Región Metropolitana de Santiago     15069
16                              Región De Antofagasta      1405
17                         Región De Arica Parinacota       324
18                                  Región De Atacama       860
19  Región De Aysén del General Carlos Ibañez del ...       345

In [20]:
df_total = df[df["OrdenCausa"] == 3].copy()

df_total["RegionGlosa"] = df_total["RegionGlosa"].replace({
    "Región De los Ríos": "Región De Los Ríos"
})

df_total = df_total.dropna(subset=["RegionGlosa"])

df_semanal = (
    df_total
    .groupby(
        ["Anio", "SemanaEstadistica", "RegionGlosa"],
        as_index=False
    )["NumTotal"]
    .sum()
)

In [21]:
print(df_semanal["NumTotal"].describe())

count    10640.000000
mean      5316.363064
std       8310.658425
min         40.000000
25%       1176.750000
50%       2702.000000
75%       5699.250000
max      77566.000000
Name: NumTotal, dtype: float64

In [22]:
# Ver el comportamiento resumido por cada región
print(df_semanal.groupby("RegionGlosa")["NumTotal"].agg(["mean", "max", "count"]))

                                                            mean    max  count
RegionGlosa
Región De Antofagasta                                2391.422556   5222    665
Región De Arica Parinacota                            829.882707   2245    665
Región De Atacama                                    1749.836090   4988    665
Región De Aysén del General Carlos Ibañez del C...    593.815038   1753    665
Región De Coquimbo                                   3081.625564   7610    665
Región De La Araucanía                               4132.018045  11461    665
Región De Los Lagos                                  5125.133835  11399    665
Región De Los Ríos                                   2682.890226   6351    665
Región De Magallanes y de la Antártica Chilena       1020.944361   2848    665
Región De Tarapacá                                   1811.088722   4741    665
Región De Valparaíso                                 7180.273684  19126    665
Región De Ñuble                                      2117.222556   6612    665
Región Del Bíobío                                   10643.906767  23946    665
Región Del Libertador Gral. B. O'Higgins             4299.696241  12207    665
Región Del Maule                                     7006.560902  17656    665
Región Metropolitana de Santiago                    30395.491729  77566    665

In [18]:
umbral = df_semanal["NumTotal"].quantile(0.75)

0 = sería demanda normal

1 = srría semana dentro del 25% de mayor demanda

# Machine Learning
## Creación de variables temporales

In [39]:
# Ordenar cronológicamente por región
df_modelo = df_semanal.sort_values(
    ["RegionGlosa", "Anio", "SemanaEstadistica"]
).copy()

df_modelo.head()

    Anio  SemanaEstadistica            RegionGlosa  NumTotal
0   2014                  1  Región De Antofagasta       808
16  2014                  2  Región De Antofagasta      1405
32  2014                  3  Región De Antofagasta      1315
48  2014                  4  Región De Antofagasta      1442
64  2014                  5  Región De Antofagasta      1355

In [40]:
# Atenciones de semanas anteriores
df_modelo["lag_1"] = (
    df_modelo.groupby("RegionGlosa")["NumTotal"].shift(1)
)

df_modelo["lag_2"] = (
    df_modelo.groupby("RegionGlosa")["NumTotal"].shift(2)
)

df_modelo["lag_3"] = (
    df_modelo.groupby("RegionGlosa")["NumTotal"].shift(3)
)

In [41]:
df_modelo["promedio_3_semanas"] = (
    df_modelo[["lag_1", "lag_2", "lag_3"]]
    .mean(axis=1)
)

In [ ]:
#calcular el percentil 75 por región
umbrales = (
    df_modelo.groupby("RegionGlosa")["NumTotal"]
    .quantile(0.75)
)

umbrales

RegionGlosa
Región De Antofagasta                                   3305.0
Región De Arica Parinacota                              1122.0
Región De Atacama                                       2387.0
Región De Aysén del General Carlos Ibañez del Campo      826.0
Región De Coquimbo                                      4256.0
Región De La Araucanía                                  5668.0
Región De Los Lagos                                     7076.0
Región De Los Ríos                                      3718.0
Región De Magallanes y de la Antártica Chilena          1399.0
Región De Tarapacá                                      2414.0
Región De Valparaíso                                    9898.0
Región De Ñuble                                         2926.0
Región Del Bíobío                                      14783.0
Región Del Libertador Gral. B. O'Higgins                5893.0
Región Del Maule                                        9682.0
Región Metropolitana de Santiago                       40194.0
Name: NumTotal, dtype: float64

In [ ]:
#umbral para cada registro
df_modelo["umbral_alta_demanda"] = (
    df_modelo["RegionGlosa"].map(umbrales)
)

In [ ]:
#clasificar siguiente semana; no actual
df_modelo["NumTotal_siguiente"] = (
    df_modelo.groupby("RegionGlosa")["NumTotal"].shift(-1)
)

In [48]:
#definición de demanda
df_modelo["AltaDemanda"] = (
    df_modelo["NumTotal_siguiente"]
    >= df_modelo["umbral_alta_demanda"]
).astype(int)

In [ ]:
#remover blancos comportamientos anteriores
df_modelo = df_modelo.dropna(
    subset=[
        "lag_1",
        "lag_2",
        "lag_3",
        "NumTotal_siguiente"
    ]
).copy()

In [53]:
df_modelo[
    [
        "Anio",
        "SemanaEstadistica",
        "RegionGlosa",
        "NumTotal",
        "lag_1",
        "lag_2",
        "lag_3",
        "promedio_3_semanas",
        "NumTotal_siguiente",
        "AltaDemanda"
    ]
].head(20)

,Anio,SemanaEstadistica,RegionGlosa,NumTotal,lag_1,lag_2,lag_3,promedio_3_semanas,NumTotal_siguiente,AltaDemanda
48,2014,4,Región De Antofagasta,1442,1315.0,1405.0,808.0,1176.000000,1355.0,0
64,2014,5,Región De Antofagasta,1355,1442.0,1315.0,1405.0,1387.333333,1366.0,0
80,2014,6,Región De Antofagasta,1366,1355.0,1442.0,1315.0,1370.666667,1242.0,0
96,2014,7,Región De Antofagasta,1242,1366.0,1355.0,1442.0,1387.666667,1247.0,0
112,2014,8,Región De Antofagasta,1247,1242.0,1366.0,1355.0,1321.000000,1239.0,0
128,2014,9,Región De Antofagasta,1239,1247.0,1242.0,1366.0,1285.000000,1306.0,0
144,2014,10,Región De Antofagasta,1306,1239.0,1247.0,1242.0,1242.666667,1609.0,0
160,2014,11,Región De Antofagasta,1609,1306.0,1239.0,1247.0,1264.000000,2242.0,0
176,2014,12,Región De Antofagasta,2242,1609.0,1306.0,1239.0,1384.666667,2352.0,0
192,2014,13,Región De Antofagasta,2352,2242.0,1609.0,1306.0,1719.000000,2051.0,0
208,2014,14,Región De Antofagasta,2051,2352.0,2242.0,1609.0,2067.666667,1957.0,0
224,2014,15,Región De Antofagasta,1957,2051.0,2352.0,2242.0,2215.000000,1883.0,0
240,2014,16,Región De Antofagasta,1883,1957.0,2051.0,2352.0,2120.000000,2248.0,0
256,2014,17,Región De Antofagasta,2248,1883.0,1957.0,2051.0,1963.666667,1930.0,0
272,2014,18,Región De Antofagasta,1930,2248.0,1883.0,1957.0,2029.333333,1922.0,0
288,2014,19,Región De Antofagasta,1922,1930.0,2248.0,1883.0,2020.333333,2110.0,0
304,2014,20,Región De Antofagasta,2110,1922.0,1930.0,2248.0,2033.333333,2396.0,0
320,2014,21,Región De Antofagasta,2396,2110.0,1922.0,1930.0,1987.333333,2458.0,0
336,2014,22,Región De Antofagasta,2458,2396.0,2110.0,1922.0,2142.666667,2660.0,0
352,2014,23,Región De Antofagasta,2660,2458.0,2396.0,2110.0,2321.333333,2733.0,0

In [50]:
df_modelo["AltaDemanda"].value_counts()

AltaDemanda
0    7903
1    2673
Name: count, dtype: int64

In [51]:
df_modelo["AltaDemanda"].value_counts(normalize=True)

AltaDemanda
0    0.747258
1    0.252742
Name: proportion, dtype: float64

## X e Y

In [54]:
features = [
    "SemanaEstadistica",
    "lag_1",
    "lag_2",
    "lag_3",
    "promedio_3_semanas"
]

X = df_modelo[features]
y = df_modelo["AltaDemanda"]

print(X.shape)
print(y.shape)

(10576, 5)
(10576,)

## train & test

In [55]:
train = df_modelo[df_modelo["Anio"] <= 2024]
test = df_modelo[df_modelo["Anio"] >= 2025]

In [56]:
X_train = train[features]
y_train = train["AltaDemanda"]

X_test = test[features]
y_test = test["AltaDemanda"]

print(X_train.shape)
print(X_test.shape)

(9168, 5)
(1408, 5)

## estandarización

In [57]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## regresión logística

In [59]:
from sklearn.linear_model import LogisticRegression

modelo = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

modelo.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

## predicción

In [61]:
y_pred = modelo.predict(X_test_scaled)

y_prob = modelo.predict_proba(X_test_scaled)[:, 1]

In [64]:
y_prob

array([0.26775533, 0.19332855, 0.29217963, ..., 0.9972183 , 0.99535509,
       0.81206668], shape=(1408,))

## Evaluación

In [65]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nROC-AUC:")
print(roc_auc_score(y_test, y_prob))

Accuracy: 0.6640625

Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.73      0.74       909
           1       0.53      0.55      0.54       499

    accuracy                           0.66      1408
   macro avg       0.64      0.64      0.64      1408
weighted avg       0.67      0.66      0.67      1408


Confusion Matrix:
[[662 247]
 [226 273]]

ROC-AUC:
0.7309624750050157

# Modelo final

In [66]:
features_finales = [
    "SemanaEstadistica",
    "RegionGlosa",
    "lag_1",
    "lag_2",
    "lag_3",
    "promedio_3_semanas"
]

In [67]:
X_train = train[features_finales]
y_train = train["AltaDemanda"]

X_test = test[features_finales]
y_test = test["AltaDemanda"]

In [68]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

In [69]:
variables_numericas = [
    "SemanaEstadistica",
    "lag_1",
    "lag_2",
    "lag_3",
    "promedio_3_semanas"
]

variables_categoricas = [
    "RegionGlosa"
]

In [70]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            variables_numericas
        ),
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            variables_categoricas
        )
    ]
)

In [71]:
modelo_final = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "classifier",
            LogisticRegression(
                max_iter=1000,
                class_weight="balanced"
            )
        )
    ]
)

In [72]:
modelo_final.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SemanaEstadistica', 'lag_1',
                                                   'lag_2', 'lag_3',
                                                   'promedio_3_semanas']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['RegionGlosa'])])),
                ('classifier',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [74]:
y_pred_final = modelo_final.predict(X_test)

y_prob_final = modelo_final.predict_proba(X_test)[:, 1]

In [75]:
print("Accuracy:", accuracy_score(y_test, y_pred_final))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_final))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_final))

print("\nROC-AUC:")
print(roc_auc_score(y_test, y_prob_final))

Accuracy: 0.7414772727272727

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.69      0.77       909
           1       0.60      0.84      0.70       499

    accuracy                           0.74      1408
   macro avg       0.74      0.76      0.74      1408
weighted avg       0.78      0.74      0.75      1408


Confusion Matrix:
[[626 283]
 [ 81 418]]

ROC-AUC:
0.815803223608934

## Exportación del modelo

In [76]:
import pickle

with open("modelo.pkl", "wb") as archivo:
    pickle.dump(modelo_final, archivo)

print("Modelo guardado correctamente")

Modelo guardado correctamente

In [77]:
with open("modelo.pkl", "rb") as archivo:
    modelo_cargado = pickle.load(archivo)

print(modelo_cargado)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SemanaEstadistica', 'lag_1',
                                                   'lag_2', 'lag_3',
                                                   'promedio_3_semanas']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['RegionGlosa'])])),
                ('classifier',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])